name = "TinOpener"
uuid = "6fd7c553-ba03-4330-918c-b18410755bc0"
authors = ["Henri Kauhanen"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
